services:
  backend:
    build: ./backend
    ports:
      - "8080:3000"  
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  
